system:
  update_rate: 100  # Hz
  memory_size: 1000  # entries

modules:
  watchdog:
    enabled: true
    check_interval: 1.0  # seconds
    heartbeat_timeout: 5.0  # seconds
    heartbeat_warning: 2.0  # seconds
    auto_restart: true
    max_restart_attempts: 3
    recovery_strategy: "restart"  # restart, reset, degrade, stop
    recovery_cooldown: 5.0
    alerts:
      console: true
      sound: false
      
  input:
    enabled: true
    keyboard_mapping: "wasd"  # wasd, arrows
    mouse_sensitivity: 1.0
    mouse_deadzone: 5  # pixels
    update_rate: 60
    buffer_size: 100
    heartbeat_interval: 0.5
    # Mouse end-effector control
    enable_end_effector_control: true
    screen_width: 1920
    screen_height: 1080
    workspace_width: 1.2  # meters
    workspace_height: 1.2  # meters
    workspace_center: [0.4, 0.0, 0.4]  # robot coordinates
    position_sensitivity: 1.0
    scroll_sensitivity: 0.02  # meters per scroll
    enable_smoothing: true
    smoothing_factor: 0.7
    
  sense:
    enabled: true
    filter_noise: true
    update_rate: 50
    sensor_update_rate: 50  # Hz for continuous sensor readings
    heartbeat_interval: 0.5
    
  plan:
    enabled: true
    algorithm: "simple"  # simple, advanced
    update_rate: 30
    heartbeat_interval: 0.5
    
  act:
    enabled: true
    control_mode: "position"  # position, velocity, torque
    update_rate: 100
    heartbeat_interval: 0.5
    # End-effector control parameters
    control_frequency: 100  # Hz
    position_tolerance: 0.005  # 5mm
    max_joint_velocity: 2.0  # rad/s
    use_jacobian_ik: true  # Use faster Jacobian-based IK
    enable_safety_checks: true
    workspace_margin: 0.05  # 5cm safety margin
    # Inverse kinematics parameters
    kinematics:
      max_iterations: 100
      position_tolerance: 0.001
      orientation_tolerance: 0.01
    
  robot:
    enabled: true
    update_rate: 50
    heartbeat_interval: 0.5
    safety_checks: true
    collision_detection: true
    history_size: 100
    joint_names: ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    joint_limits: [[-3.14, 3.14], [-3.14, 3.14], [-3.14, 3.14], [-3.14, 3.14], [-3.14, 3.14], [-3.14, 3.14]]
    max_velocities: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    max_accelerations: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
    home_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    workspace_limits:
      x: [-1.0, 1.0]
      y: [-1.0, 1.0] 
      z: [0.0, 2.0]
    
  output:
    enabled: true
    format: "json"
    update_rate: 100
    heartbeat_interval: 0.5

adapter:
  type: "mujoco"  # mujoco, real_robot
  model_path: "assets/robots/arm/ur5e.xml"
  render: true
  physics_timestep: 0.001
  control_timestep: 0.01
  joint_names: ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
  actuator_names: ["shoulder_pan", "shoulder_lift", "elbow", "wrist_1", "wrist_2", "wrist_3"]
  end_effector_body: "wrist_3_link"
  gripper_joint: null

logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  colorful: true
  file: null  # Optional log file path

display:
  show_status: true
  status_interval: 1.0
  dashboard_enabled: true